### ISSUE TITLE
这个播放地址的api有么

### ISSUE THREAD

**Issue by lwlizhe** [yoyiyi/bilisoleil#1]
现在看了下，视频是固定写死的一个地址……话说这个b站的视频播放链接是不是都做了防盗链

**Comment by yoyiyi** [comment]
抓包抓了好几个，不过过一段时间就会失效，b站播放地址能够解析到的，但是吗，貌似做了限制，一播放权限拒绝，放在网页端就可以播放，不了解他是啥机制。。。

**Comment by lwlizhe** [comment]
在网页端你还能播放啊…………我这网页打开也是拒绝，做了防盗链了

**Comment by yoyiyi** [comment]
额，还真是，我以前搞的时候还可以，现在有不行了。。。
